### PR TITLE
BFS #running

### PR DESCRIPTION
**Pull request by ashumeow**
all well now

### CODE REVIEW

**Comment by ashumeow** [comment]
Merge it! (O_O) Why you closed it?

**Comment by ashumeow** [comment]
:( :(

https://github.com/ashumeow/DSA/commit/042ac5d51b7a6e6d27e107c13a65750b0b35789a

https://github.com/ashumeow/DSA/commit/f8981481e66f079154b706b45629f45fcf7728b8

**Comment by iamOgunyinka** [comment]
The changes you made were not too significant, git diff showed that the only change you made was removing `_bst.remove( 23 )` in `main` and nothing else. Also, the `breadth_first_traversal` I sent you was already working but the change in commit [f898148](https://github.com/ashumeow/DSA/commit/f8981481e66f079154b706b45629f45fcf7728b8) didn't work and might cause an infinite loop if merged. I had to remove it, sorry.

**Comment by ashumeow** [comment]
FINE!

**Comment by ashumeow** [comment]
i deleted that repo. I can learn C++14 all by myself. And so, i can merge my algorithm stuffs independently. (-_-)

**Pull request closed without merging**
